# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XSquare_check" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_AXI_LITE_RGB_1_N_BASEADDR" \
        "C_S_AXI_AXI_LITE_RGB_1_N_HIGHADDR" \
        "C_S_AXI_AXI_LITE_RGB_2_BASEADDR" \
        "C_S_AXI_AXI_LITE_RGB_2_HIGHADDR"

    xdefine_config_file $drv_handle "xsquare_check_g.c" "XSquare_check" \
        "DEVICE_ID" \
        "C_S_AXI_AXI_LITE_RGB_1_N_BASEADDR" \
        "C_S_AXI_AXI_LITE_RGB_2_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XSquare_check" \
        "DEVICE_ID" \
        "C_S_AXI_AXI_LITE_RGB_1_N_BASEADDR" \
        "C_S_AXI_AXI_LITE_RGB_1_N_HIGHADDR" \
        "C_S_AXI_AXI_LITE_RGB_2_BASEADDR" \
        "C_S_AXI_AXI_LITE_RGB_2_HIGHADDR"
}

