# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_2/fmchc_python1300c_xbar_2.xci
# IP: The module: 'fmchc_python1300c_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_2/fmchc_python1300c_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmchc_python1300c_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_2/fmchc_python1300c_xbar_2.xci
# IP: The module: 'fmchc_python1300c_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_2/fmchc_python1300c_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmchc_python1300c_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
