-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dataflow_parent_loop_1 is
port (
    m_axi_rgb1_in_AWVALID : OUT STD_LOGIC;
    m_axi_rgb1_in_AWREADY : IN STD_LOGIC;
    m_axi_rgb1_in_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb1_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb1_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb1_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb1_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb1_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb1_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_WVALID : OUT STD_LOGIC;
    m_axi_rgb1_in_WREADY : IN STD_LOGIC;
    m_axi_rgb1_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb1_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_WLAST : OUT STD_LOGIC;
    m_axi_rgb1_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_ARVALID : OUT STD_LOGIC;
    m_axi_rgb1_in_ARREADY : IN STD_LOGIC;
    m_axi_rgb1_in_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb1_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb1_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb1_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb1_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb1_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb1_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb1_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_RVALID : IN STD_LOGIC;
    m_axi_rgb1_in_RREADY : OUT STD_LOGIC;
    m_axi_rgb1_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb1_in_RLAST : IN STD_LOGIC;
    m_axi_rgb1_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb1_in_BVALID : IN STD_LOGIC;
    m_axi_rgb1_in_BREADY : OUT STD_LOGIC;
    m_axi_rgb1_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb1_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb1_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    rgb1_in1 : IN STD_LOGIC_VECTOR (29 downto 0);
    m_axi_rgb2_in_AWVALID : OUT STD_LOGIC;
    m_axi_rgb2_in_AWREADY : IN STD_LOGIC;
    m_axi_rgb2_in_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb2_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb2_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb2_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb2_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb2_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb2_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_WVALID : OUT STD_LOGIC;
    m_axi_rgb2_in_WREADY : IN STD_LOGIC;
    m_axi_rgb2_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb2_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_WLAST : OUT STD_LOGIC;
    m_axi_rgb2_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_ARVALID : OUT STD_LOGIC;
    m_axi_rgb2_in_ARREADY : IN STD_LOGIC;
    m_axi_rgb2_in_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb2_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb2_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb2_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb2_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb2_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_rgb2_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_rgb2_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_RVALID : IN STD_LOGIC;
    m_axi_rgb2_in_RREADY : OUT STD_LOGIC;
    m_axi_rgb2_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_rgb2_in_RLAST : IN STD_LOGIC;
    m_axi_rgb2_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb2_in_BVALID : IN STD_LOGIC;
    m_axi_rgb2_in_BREADY : OUT STD_LOGIC;
    m_axi_rgb2_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_rgb2_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_rgb2_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    rgb2_in3 : IN STD_LOGIC_VECTOR (29 downto 0);
    n_Mat_buff_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    n_Mat_buff_ce0 : OUT STD_LOGIC;
    n_Mat_buff_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    n_Mat_buff_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    n_Mat_buff_we0 : OUT STD_LOGIC;
    n_Mat_buff_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    n_Mat_buff_ce1 : OUT STD_LOGIC;
    n_Mat_buff_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    n_Mat_buff_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    n_Mat_buff_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    rgb1_in1_ap_vld : IN STD_LOGIC;
    rgb2_in3_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of dataflow_parent_loop_1 is 
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WVALID : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WLAST : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_RREADY : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_BREADY : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WVALID : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WLAST : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_RREADY : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_BREADY : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_ce0 : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_d0 : STD_LOGIC_VECTOR (17 downto 0);
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_we0 : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_ce1 : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_d1 : STD_LOGIC_VECTOR (17 downto 0);
    signal dataflow_in_loop_Loo_1_U0_n_Mat_buff_we1 : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_ap_continue : STD_LOGIC;
    signal ap_hs_continue : STD_LOGIC;
    signal ap_hs_done : STD_LOGIC;
    signal ap_hs_ready : STD_LOGIC;
    signal dataflow_in_loop_Loo_1_U0_start_state : STD_LOGIC := '0';
    signal dataflow_in_loop_Loo_1_U0_start_cnt : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal dataflow_in_loop_Loo_1_U0_done_cnt : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal dataflow_in_loop_Loo_1_U0_CS : STD_LOGIC := '0';

    component dataflow_in_loop_Loo_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        m_axi_rgb1_in_AWVALID : OUT STD_LOGIC;
        m_axi_rgb1_in_AWREADY : IN STD_LOGIC;
        m_axi_rgb1_in_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb1_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb1_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb1_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb1_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb1_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb1_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_WVALID : OUT STD_LOGIC;
        m_axi_rgb1_in_WREADY : IN STD_LOGIC;
        m_axi_rgb1_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb1_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_WLAST : OUT STD_LOGIC;
        m_axi_rgb1_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_ARVALID : OUT STD_LOGIC;
        m_axi_rgb1_in_ARREADY : IN STD_LOGIC;
        m_axi_rgb1_in_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb1_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb1_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb1_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb1_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb1_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb1_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb1_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_RVALID : IN STD_LOGIC;
        m_axi_rgb1_in_RREADY : OUT STD_LOGIC;
        m_axi_rgb1_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb1_in_RLAST : IN STD_LOGIC;
        m_axi_rgb1_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb1_in_BVALID : IN STD_LOGIC;
        m_axi_rgb1_in_BREADY : OUT STD_LOGIC;
        m_axi_rgb1_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb1_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb1_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        rgb1_in1 : IN STD_LOGIC_VECTOR (29 downto 0);
        row_0_i_i : IN STD_LOGIC_VECTOR (6 downto 0);
        m_axi_rgb2_in_AWVALID : OUT STD_LOGIC;
        m_axi_rgb2_in_AWREADY : IN STD_LOGIC;
        m_axi_rgb2_in_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb2_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb2_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb2_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb2_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb2_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb2_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_WVALID : OUT STD_LOGIC;
        m_axi_rgb2_in_WREADY : IN STD_LOGIC;
        m_axi_rgb2_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb2_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_WLAST : OUT STD_LOGIC;
        m_axi_rgb2_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_ARVALID : OUT STD_LOGIC;
        m_axi_rgb2_in_ARREADY : IN STD_LOGIC;
        m_axi_rgb2_in_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb2_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb2_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb2_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb2_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb2_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_rgb2_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_rgb2_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_RVALID : IN STD_LOGIC;
        m_axi_rgb2_in_RREADY : OUT STD_LOGIC;
        m_axi_rgb2_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_rgb2_in_RLAST : IN STD_LOGIC;
        m_axi_rgb2_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb2_in_BVALID : IN STD_LOGIC;
        m_axi_rgb2_in_BREADY : OUT STD_LOGIC;
        m_axi_rgb2_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_rgb2_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_rgb2_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        rgb2_in3 : IN STD_LOGIC_VECTOR (29 downto 0);
        n_Mat_buff_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        n_Mat_buff_ce0 : OUT STD_LOGIC;
        n_Mat_buff_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        n_Mat_buff_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        n_Mat_buff_we0 : OUT STD_LOGIC;
        n_Mat_buff_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        n_Mat_buff_ce1 : OUT STD_LOGIC;
        n_Mat_buff_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        n_Mat_buff_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
        n_Mat_buff_we1 : OUT STD_LOGIC;
        row_0_i_i_ap_vld : IN STD_LOGIC;
        rgb1_in1_ap_vld : IN STD_LOGIC;
        rgb2_in3_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_Loo_1_U0 : component dataflow_in_loop_Loo_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        m_axi_rgb1_in_AWVALID => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWVALID,
        m_axi_rgb1_in_AWREADY => ap_const_logic_0,
        m_axi_rgb1_in_AWADDR => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWADDR,
        m_axi_rgb1_in_AWID => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWID,
        m_axi_rgb1_in_AWLEN => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWLEN,
        m_axi_rgb1_in_AWSIZE => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWSIZE,
        m_axi_rgb1_in_AWBURST => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWBURST,
        m_axi_rgb1_in_AWLOCK => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWLOCK,
        m_axi_rgb1_in_AWCACHE => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWCACHE,
        m_axi_rgb1_in_AWPROT => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWPROT,
        m_axi_rgb1_in_AWQOS => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWQOS,
        m_axi_rgb1_in_AWREGION => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWREGION,
        m_axi_rgb1_in_AWUSER => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_AWUSER,
        m_axi_rgb1_in_WVALID => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WVALID,
        m_axi_rgb1_in_WREADY => ap_const_logic_0,
        m_axi_rgb1_in_WDATA => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WDATA,
        m_axi_rgb1_in_WSTRB => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WSTRB,
        m_axi_rgb1_in_WLAST => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WLAST,
        m_axi_rgb1_in_WID => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WID,
        m_axi_rgb1_in_WUSER => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_WUSER,
        m_axi_rgb1_in_ARVALID => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARVALID,
        m_axi_rgb1_in_ARREADY => m_axi_rgb1_in_ARREADY,
        m_axi_rgb1_in_ARADDR => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARADDR,
        m_axi_rgb1_in_ARID => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARID,
        m_axi_rgb1_in_ARLEN => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARLEN,
        m_axi_rgb1_in_ARSIZE => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARSIZE,
        m_axi_rgb1_in_ARBURST => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARBURST,
        m_axi_rgb1_in_ARLOCK => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARLOCK,
        m_axi_rgb1_in_ARCACHE => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARCACHE,
        m_axi_rgb1_in_ARPROT => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARPROT,
        m_axi_rgb1_in_ARQOS => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARQOS,
        m_axi_rgb1_in_ARREGION => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARREGION,
        m_axi_rgb1_in_ARUSER => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARUSER,
        m_axi_rgb1_in_RVALID => m_axi_rgb1_in_RVALID,
        m_axi_rgb1_in_RREADY => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_RREADY,
        m_axi_rgb1_in_RDATA => m_axi_rgb1_in_RDATA,
        m_axi_rgb1_in_RLAST => m_axi_rgb1_in_RLAST,
        m_axi_rgb1_in_RID => m_axi_rgb1_in_RID,
        m_axi_rgb1_in_RUSER => m_axi_rgb1_in_RUSER,
        m_axi_rgb1_in_RRESP => m_axi_rgb1_in_RRESP,
        m_axi_rgb1_in_BVALID => ap_const_logic_0,
        m_axi_rgb1_in_BREADY => dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_BREADY,
        m_axi_rgb1_in_BRESP => ap_const_lv2_0,
        m_axi_rgb1_in_BID => ap_const_lv1_0,
        m_axi_rgb1_in_BUSER => ap_const_lv1_0,
        rgb1_in1 => rgb1_in1,
        row_0_i_i => dataflow_in_loop_Loo_1_U0_start_cnt,
        m_axi_rgb2_in_AWVALID => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWVALID,
        m_axi_rgb2_in_AWREADY => ap_const_logic_0,
        m_axi_rgb2_in_AWADDR => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWADDR,
        m_axi_rgb2_in_AWID => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWID,
        m_axi_rgb2_in_AWLEN => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWLEN,
        m_axi_rgb2_in_AWSIZE => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWSIZE,
        m_axi_rgb2_in_AWBURST => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWBURST,
        m_axi_rgb2_in_AWLOCK => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWLOCK,
        m_axi_rgb2_in_AWCACHE => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWCACHE,
        m_axi_rgb2_in_AWPROT => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWPROT,
        m_axi_rgb2_in_AWQOS => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWQOS,
        m_axi_rgb2_in_AWREGION => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWREGION,
        m_axi_rgb2_in_AWUSER => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_AWUSER,
        m_axi_rgb2_in_WVALID => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WVALID,
        m_axi_rgb2_in_WREADY => ap_const_logic_0,
        m_axi_rgb2_in_WDATA => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WDATA,
        m_axi_rgb2_in_WSTRB => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WSTRB,
        m_axi_rgb2_in_WLAST => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WLAST,
        m_axi_rgb2_in_WID => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WID,
        m_axi_rgb2_in_WUSER => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_WUSER,
        m_axi_rgb2_in_ARVALID => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARVALID,
        m_axi_rgb2_in_ARREADY => m_axi_rgb2_in_ARREADY,
        m_axi_rgb2_in_ARADDR => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARADDR,
        m_axi_rgb2_in_ARID => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARID,
        m_axi_rgb2_in_ARLEN => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARLEN,
        m_axi_rgb2_in_ARSIZE => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARSIZE,
        m_axi_rgb2_in_ARBURST => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARBURST,
        m_axi_rgb2_in_ARLOCK => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARLOCK,
        m_axi_rgb2_in_ARCACHE => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARCACHE,
        m_axi_rgb2_in_ARPROT => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARPROT,
        m_axi_rgb2_in_ARQOS => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARQOS,
        m_axi_rgb2_in_ARREGION => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARREGION,
        m_axi_rgb2_in_ARUSER => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARUSER,
        m_axi_rgb2_in_RVALID => m_axi_rgb2_in_RVALID,
        m_axi_rgb2_in_RREADY => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_RREADY,
        m_axi_rgb2_in_RDATA => m_axi_rgb2_in_RDATA,
        m_axi_rgb2_in_RLAST => m_axi_rgb2_in_RLAST,
        m_axi_rgb2_in_RID => m_axi_rgb2_in_RID,
        m_axi_rgb2_in_RUSER => m_axi_rgb2_in_RUSER,
        m_axi_rgb2_in_RRESP => m_axi_rgb2_in_RRESP,
        m_axi_rgb2_in_BVALID => ap_const_logic_0,
        m_axi_rgb2_in_BREADY => dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_BREADY,
        m_axi_rgb2_in_BRESP => ap_const_lv2_0,
        m_axi_rgb2_in_BID => ap_const_lv1_0,
        m_axi_rgb2_in_BUSER => ap_const_lv1_0,
        rgb2_in3 => rgb2_in3,
        n_Mat_buff_address0 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_address0,
        n_Mat_buff_ce0 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_ce0,
        n_Mat_buff_d0 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_d0,
        n_Mat_buff_q0 => ap_const_lv18_0,
        n_Mat_buff_we0 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_we0,
        n_Mat_buff_address1 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_address1,
        n_Mat_buff_ce1 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_ce1,
        n_Mat_buff_d1 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_d1,
        n_Mat_buff_q1 => ap_const_lv18_0,
        n_Mat_buff_we1 => dataflow_in_loop_Loo_1_U0_n_Mat_buff_we1,
        row_0_i_i_ap_vld => ap_const_logic_0,
        rgb1_in1_ap_vld => rgb1_in1_ap_vld,
        rgb2_in3_ap_vld => rgb2_in3_ap_vld,
        ap_done => dataflow_in_loop_Loo_1_U0_ap_done,
        ap_start => dataflow_in_loop_Loo_1_U0_ap_start,
        ap_ready => dataflow_in_loop_Loo_1_U0_ap_ready,
        ap_idle => dataflow_in_loop_Loo_1_U0_ap_idle,
        ap_continue => dataflow_in_loop_Loo_1_U0_ap_continue);





    dataflow_in_loop_Loo_1_U0_CS_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                dataflow_in_loop_Loo_1_U0_CS <= ap_const_logic_0;
            else
                if (((ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_done_cnt) and (ap_const_logic_1 = ap_continue))) then 
                    dataflow_in_loop_Loo_1_U0_CS <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_start)) then 
                    dataflow_in_loop_Loo_1_U0_CS <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    dataflow_in_loop_Loo_1_U0_done_cnt_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                dataflow_in_loop_Loo_1_U0_done_cnt <= ap_const_lv7_0;
            else
                if (((dataflow_in_loop_Loo_1_U0_ap_done = ap_const_logic_1) and not((ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_done_cnt)))) then 
                    dataflow_in_loop_Loo_1_U0_done_cnt <= std_logic_vector(unsigned(dataflow_in_loop_Loo_1_U0_done_cnt) + unsigned(ap_const_lv7_1));
                elsif (((ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_done_cnt) and (ap_const_logic_1 = ap_continue))) then 
                    dataflow_in_loop_Loo_1_U0_done_cnt <= ap_const_lv7_0;
                end if; 
            end if;
        end if;
    end process;


    dataflow_in_loop_Loo_1_U0_start_cnt_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                dataflow_in_loop_Loo_1_U0_start_cnt <= ap_const_lv7_0;
            else
                if (((ap_const_logic_1 = dataflow_in_loop_Loo_1_U0_start_state) and (dataflow_in_loop_Loo_1_U0_ap_ready = ap_const_logic_1))) then 
                    dataflow_in_loop_Loo_1_U0_start_cnt <= std_logic_vector(unsigned(dataflow_in_loop_Loo_1_U0_start_cnt) + unsigned(ap_const_lv7_1));
                elsif (((ap_const_logic_1 = dataflow_in_loop_Loo_1_U0_start_state) and (ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_start_cnt))) then 
                    dataflow_in_loop_Loo_1_U0_start_cnt <= ap_const_lv7_0;
                end if; 
            end if;
        end if;
    end process;


    dataflow_in_loop_Loo_1_U0_start_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                dataflow_in_loop_Loo_1_U0_start_state <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_start) and (ap_const_logic_0 = dataflow_in_loop_Loo_1_U0_start_state))) then 
                    dataflow_in_loop_Loo_1_U0_start_state <= ap_const_logic_1;
                elsif (((ap_const_logic_1 = dataflow_in_loop_Loo_1_U0_start_state) and (ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_start_cnt))) then 
                    dataflow_in_loop_Loo_1_U0_start_state <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_in_loop_Loo_1_U0_done_cnt, dataflow_in_loop_Loo_1_U0_CS)
    begin
        if (((ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_done_cnt) and (ap_const_logic_1 = dataflow_in_loop_Loo_1_U0_CS))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_hs_continue <= ap_continue;
    ap_hs_done <= dataflow_in_loop_Loo_1_U0_ap_done;
    ap_hs_ready <= dataflow_in_loop_Loo_1_U0_ap_ready;
    ap_idle <= dataflow_in_loop_Loo_1_U0_ap_idle;

    ap_ready_assign_proc : process(dataflow_in_loop_Loo_1_U0_start_cnt)
    begin
        if ((ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_start_cnt)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_Loo_1_U0_ap_continue <= ap_const_logic_1;

    dataflow_in_loop_Loo_1_U0_ap_start_assign_proc : process(dataflow_in_loop_Loo_1_U0_start_state, dataflow_in_loop_Loo_1_U0_start_cnt)
    begin
        if (((ap_const_logic_1 = dataflow_in_loop_Loo_1_U0_start_state) and not((ap_const_lv7_40 = dataflow_in_loop_Loo_1_U0_start_cnt)))) then 
            dataflow_in_loop_Loo_1_U0_ap_start <= ap_const_logic_1;
        else 
            dataflow_in_loop_Loo_1_U0_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_rgb1_in_ARADDR <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARADDR;
    m_axi_rgb1_in_ARBURST <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARBURST;
    m_axi_rgb1_in_ARCACHE <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARCACHE;
    m_axi_rgb1_in_ARID <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARID;
    m_axi_rgb1_in_ARLEN <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARLEN;
    m_axi_rgb1_in_ARLOCK <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARLOCK;
    m_axi_rgb1_in_ARPROT <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARPROT;
    m_axi_rgb1_in_ARQOS <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARQOS;
    m_axi_rgb1_in_ARREGION <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARREGION;
    m_axi_rgb1_in_ARSIZE <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARSIZE;
    m_axi_rgb1_in_ARUSER <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARUSER;
    m_axi_rgb1_in_ARVALID <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_ARVALID;
    m_axi_rgb1_in_AWADDR <= ap_const_lv32_0;
    m_axi_rgb1_in_AWBURST <= ap_const_lv2_0;
    m_axi_rgb1_in_AWCACHE <= ap_const_lv4_0;
    m_axi_rgb1_in_AWID <= ap_const_lv1_0;
    m_axi_rgb1_in_AWLEN <= ap_const_lv32_0;
    m_axi_rgb1_in_AWLOCK <= ap_const_lv2_0;
    m_axi_rgb1_in_AWPROT <= ap_const_lv3_0;
    m_axi_rgb1_in_AWQOS <= ap_const_lv4_0;
    m_axi_rgb1_in_AWREGION <= ap_const_lv4_0;
    m_axi_rgb1_in_AWSIZE <= ap_const_lv3_0;
    m_axi_rgb1_in_AWUSER <= ap_const_lv1_0;
    m_axi_rgb1_in_AWVALID <= ap_const_logic_0;
    m_axi_rgb1_in_BREADY <= ap_const_logic_0;
    m_axi_rgb1_in_RREADY <= dataflow_in_loop_Loo_1_U0_m_axi_rgb1_in_RREADY;
    m_axi_rgb1_in_WDATA <= ap_const_lv32_0;
    m_axi_rgb1_in_WID <= ap_const_lv1_0;
    m_axi_rgb1_in_WLAST <= ap_const_logic_0;
    m_axi_rgb1_in_WSTRB <= ap_const_lv4_0;
    m_axi_rgb1_in_WUSER <= ap_const_lv1_0;
    m_axi_rgb1_in_WVALID <= ap_const_logic_0;
    m_axi_rgb2_in_ARADDR <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARADDR;
    m_axi_rgb2_in_ARBURST <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARBURST;
    m_axi_rgb2_in_ARCACHE <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARCACHE;
    m_axi_rgb2_in_ARID <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARID;
    m_axi_rgb2_in_ARLEN <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARLEN;
    m_axi_rgb2_in_ARLOCK <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARLOCK;
    m_axi_rgb2_in_ARPROT <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARPROT;
    m_axi_rgb2_in_ARQOS <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARQOS;
    m_axi_rgb2_in_ARREGION <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARREGION;
    m_axi_rgb2_in_ARSIZE <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARSIZE;
    m_axi_rgb2_in_ARUSER <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARUSER;
    m_axi_rgb2_in_ARVALID <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_ARVALID;
    m_axi_rgb2_in_AWADDR <= ap_const_lv32_0;
    m_axi_rgb2_in_AWBURST <= ap_const_lv2_0;
    m_axi_rgb2_in_AWCACHE <= ap_const_lv4_0;
    m_axi_rgb2_in_AWID <= ap_const_lv1_0;
    m_axi_rgb2_in_AWLEN <= ap_const_lv32_0;
    m_axi_rgb2_in_AWLOCK <= ap_const_lv2_0;
    m_axi_rgb2_in_AWPROT <= ap_const_lv3_0;
    m_axi_rgb2_in_AWQOS <= ap_const_lv4_0;
    m_axi_rgb2_in_AWREGION <= ap_const_lv4_0;
    m_axi_rgb2_in_AWSIZE <= ap_const_lv3_0;
    m_axi_rgb2_in_AWUSER <= ap_const_lv1_0;
    m_axi_rgb2_in_AWVALID <= ap_const_logic_0;
    m_axi_rgb2_in_BREADY <= ap_const_logic_0;
    m_axi_rgb2_in_RREADY <= dataflow_in_loop_Loo_1_U0_m_axi_rgb2_in_RREADY;
    m_axi_rgb2_in_WDATA <= ap_const_lv32_0;
    m_axi_rgb2_in_WID <= ap_const_lv1_0;
    m_axi_rgb2_in_WLAST <= ap_const_logic_0;
    m_axi_rgb2_in_WSTRB <= ap_const_lv4_0;
    m_axi_rgb2_in_WUSER <= ap_const_lv1_0;
    m_axi_rgb2_in_WVALID <= ap_const_logic_0;
    n_Mat_buff_address0 <= dataflow_in_loop_Loo_1_U0_n_Mat_buff_address0;
    n_Mat_buff_address1 <= ap_const_lv12_0;
    n_Mat_buff_ce0 <= dataflow_in_loop_Loo_1_U0_n_Mat_buff_ce0;
    n_Mat_buff_ce1 <= ap_const_logic_0;
    n_Mat_buff_d0 <= dataflow_in_loop_Loo_1_U0_n_Mat_buff_d0;
    n_Mat_buff_d1 <= ap_const_lv18_0;
    n_Mat_buff_we0 <= dataflow_in_loop_Loo_1_U0_n_Mat_buff_we0;
    n_Mat_buff_we1 <= ap_const_logic_0;
end behav;
