# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System}]

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}]

# IP: bd/System/ip/System_GND_0/System_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_GND_0 || ORIG_REF_NAME==System_GND_0}]

# IP: bd/System/ip/System_axi_vdma_0_0/System_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_vdma_0_0 || ORIG_REF_NAME==System_axi_vdma_0_0}]

# IP: bd/System/ip/System_axi_interconnect_0_0/System_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_interconnect_0_0 || ORIG_REF_NAME==System_axi_interconnect_0_0}]

# IP: bd/System/ip/System_xbar_1/System_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xbar_1 || ORIG_REF_NAME==System_xbar_1}]

# IP: bd/System/ip/System_axi_mem_intercon_0/System_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_mem_intercon_0 || ORIG_REF_NAME==System_axi_mem_intercon_0}]

# IP: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# IP: bd/System/ip/System_xbar_2/System_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xbar_2 || ORIG_REF_NAME==System_xbar_2}]

# IP: bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_0 || ORIG_REF_NAME==System_auto_pc_0}]

# IP: bd/System/ip/System_auto_pc_1/System_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_1 || ORIG_REF_NAME==System_auto_pc_1}]

# IP: bd/System/ip/System_auto_us_0/System_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_us_0 || ORIG_REF_NAME==System_auto_us_0}]

# XDC: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/System/ip/System_axi_vdma_0_0/System_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_vdma_0_0 || ORIG_REF_NAME==System_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_vdma_0_0/System_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_vdma_0_0 || ORIG_REF_NAME==System_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_vdma_0_0/System_axi_vdma_0_0_ooc.xdc

# XDC: bd/System/ip/System_xbar_1/System_xbar_1_ooc.xdc

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/System/ip/System_xbar_2/System_xbar_2_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_1/System_auto_pc_1_ooc.xdc

# XDC: bd/System/ip/System_auto_us_0/System_auto_us_0_ooc.xdc

# XDC: bd/System/ip/System_auto_us_0/System_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_auto_us_0 || ORIG_REF_NAME==System_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/System/System_ooc.xdc
