# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Avnet/hdl/Projects/fmchc_python1300c/pz7030_fmc2_fmchc_python1300c.xdc

# Block Designs: bd/fmchc_python1300c/fmchc_python1300c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c || ORIG_REF_NAME==fmchc_python1300c}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_processing_system7_0_0/fmchc_python1300c_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_processing_system7_0_0 || ORIG_REF_NAME==fmchc_python1300c_processing_system7_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_cfa_0_0/fmchc_python1300c_v_cfa_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_cfa_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_cfa_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_cresample_0_0/fmchc_python1300c_v_cresample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_cresample_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_cresample_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_osd_0_0/fmchc_python1300c_v_osd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_osd_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_osd_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_rgb2ycrcb_0_0/fmchc_python1300c_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_rgb2ycrcb_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_tc_0_0/fmchc_python1300c_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_tc_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_tc_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_avnet_hdmi_in_0_0/fmchc_python1300c_avnet_hdmi_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_avnet_hdmi_in_0_0 || ORIG_REF_NAME==fmchc_python1300c_avnet_hdmi_in_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_avnet_hdmi_out_0_0/fmchc_python1300c_avnet_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_avnet_hdmi_out_0_0 || ORIG_REF_NAME==fmchc_python1300c_avnet_hdmi_out_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_axi_mem_intercon_0/fmchc_python1300c_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_axi_mem_intercon_0 || ORIG_REF_NAME==fmchc_python1300c_axi_mem_intercon_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_0/fmchc_python1300c_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_xbar_0 || ORIG_REF_NAME==fmchc_python1300c_xbar_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_0_0/fmchc_python1300c_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_axi_vdma_0_0 || ORIG_REF_NAME==fmchc_python1300c_axi_vdma_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_1_0/fmchc_python1300c_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_axi_vdma_1_0 || ORIG_REF_NAME==fmchc_python1300c_axi_vdma_1_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_clk_wiz_0_0/fmchc_python1300c_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_clk_wiz_0_0 || ORIG_REF_NAME==fmchc_python1300c_clk_wiz_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_fmc_hdmi_cam_iic_0_0/fmchc_python1300c_fmc_hdmi_cam_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_fmc_hdmi_cam_iic_0_0 || ORIG_REF_NAME==fmchc_python1300c_fmc_hdmi_cam_iic_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_onsemi_python_cam_0_0/fmchc_python1300c_onsemi_python_cam_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_onsemi_python_cam_0_0 || ORIG_REF_NAME==fmchc_python1300c_onsemi_python_cam_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_onsemi_python_spi_0_0/fmchc_python1300c_onsemi_python_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_onsemi_python_spi_0_0 || ORIG_REF_NAME==fmchc_python1300c_onsemi_python_spi_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_processing_system7_0_axi_periph_0/fmchc_python1300c_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==fmchc_python1300c_processing_system7_0_axi_periph_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_1/fmchc_python1300c_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_xbar_1 || ORIG_REF_NAME==fmchc_python1300c_xbar_1}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_148_5M_0/fmchc_python1300c_rst_processing_system7_0_148_5M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_rst_processing_system7_0_148_5M_0 || ORIG_REF_NAME==fmchc_python1300c_rst_processing_system7_0_148_5M_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_149M_0/fmchc_python1300c_rst_processing_system7_0_149M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_rst_processing_system7_0_149M_0 || ORIG_REF_NAME==fmchc_python1300c_rst_processing_system7_0_149M_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_76M_0/fmchc_python1300c_rst_processing_system7_0_76M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==fmchc_python1300c_rst_processing_system7_0_76M_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_axi4s_vid_out_0_0/fmchc_python1300c_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_axi4s_vid_out_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_vid_in_axi4s_0_0/fmchc_python1300c_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==fmchc_python1300c_v_vid_in_axi4s_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_v_vid_in_axi4s_1_0/fmchc_python1300c_v_vid_in_axi4s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==fmchc_python1300c_v_vid_in_axi4s_1_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_xlconstant_0_0/fmchc_python1300c_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_xlconstant_0_0 || ORIG_REF_NAME==fmchc_python1300c_xlconstant_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_xlconstant_1_0/fmchc_python1300c_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_xlconstant_1_0 || ORIG_REF_NAME==fmchc_python1300c_xlconstant_1_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_square_check_0_0/fmchc_python1300c_square_check_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_square_check_0_0 || ORIG_REF_NAME==fmchc_python1300c_square_check_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_axi_interconnect_0_0/fmchc_python1300c_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_axi_interconnect_0_0 || ORIG_REF_NAME==fmchc_python1300c_axi_interconnect_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_2/fmchc_python1300c_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_xbar_2 || ORIG_REF_NAME==fmchc_python1300c_xbar_2}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_axi_interconnect_1_0/fmchc_python1300c_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_axi_interconnect_1_0 || ORIG_REF_NAME==fmchc_python1300c_axi_interconnect_1_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_3/fmchc_python1300c_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_xbar_3 || ORIG_REF_NAME==fmchc_python1300c_xbar_3}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_proc_sys_reset_0_0/fmchc_python1300c_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_proc_sys_reset_0_0 || ORIG_REF_NAME==fmchc_python1300c_proc_sys_reset_0_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_0/fmchc_python1300c_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_auto_pc_0 || ORIG_REF_NAME==fmchc_python1300c_auto_pc_0}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_1/fmchc_python1300c_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_auto_pc_1 || ORIG_REF_NAME==fmchc_python1300c_auto_pc_1}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_2/fmchc_python1300c_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_auto_pc_2 || ORIG_REF_NAME==fmchc_python1300c_auto_pc_2}]

# IP: bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_3/fmchc_python1300c_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmchc_python1300c_auto_pc_3 || ORIG_REF_NAME==fmchc_python1300c_auto_pc_3}]

# XDC: bd/fmchc_python1300c/fmchc_python1300c_ooc.xdc
