# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z030sbg485-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.cache/wt [current_project]
set_property parent.project_path C:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:picozed_7030_fmc2:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Avnet/hdl/IP
  c:/Xilinx/Projects/RADIO_Algorithmus/Ohne_Annotations/ALG_HLS
} [current_project]
set_property ip_output_repo c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/hdl/fmchc_python1300c_wrapper.vhd
add_files C:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/fmchc_python1300c.bd
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_processing_system7_0_0/fmchc_python1300c_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_cfa_0_0/fmchc_python1300c_v_cfa_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_cfa_0_0/fmchc_python1300c_v_cfa_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_cresample_0_0/fmchc_python1300c_v_cresample_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_cresample_0_0/fmchc_python1300c_v_cresample_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_osd_0_0/fmchc_python1300c_v_osd_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_osd_0_0/fmchc_python1300c_v_osd_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_rgb2ycrcb_0_0/fmchc_python1300c_v_rgb2ycrcb_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_rgb2ycrcb_0_0/fmchc_python1300c_v_rgb2ycrcb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_tc_0_0/fmchc_python1300c_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_tc_0_0/fmchc_python1300c_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_0/fmchc_python1300c_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_0_0/fmchc_python1300c_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_0_0/fmchc_python1300c_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_0_0/fmchc_python1300c_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_1_0/fmchc_python1300c_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_1_0/fmchc_python1300c_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_axi_vdma_1_0/fmchc_python1300c_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_clk_wiz_0_0/fmchc_python1300c_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_clk_wiz_0_0/fmchc_python1300c_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_clk_wiz_0_0/fmchc_python1300c_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_fmc_hdmi_cam_iic_0_0/fmchc_python1300c_fmc_hdmi_cam_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_fmc_hdmi_cam_iic_0_0/fmchc_python1300c_fmc_hdmi_cam_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_1/fmchc_python1300c_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_148_5M_0/fmchc_python1300c_rst_processing_system7_0_148_5M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_148_5M_0/fmchc_python1300c_rst_processing_system7_0_148_5M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_148_5M_0/fmchc_python1300c_rst_processing_system7_0_148_5M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_149M_0/fmchc_python1300c_rst_processing_system7_0_149M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_149M_0/fmchc_python1300c_rst_processing_system7_0_149M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_149M_0/fmchc_python1300c_rst_processing_system7_0_149M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_76M_0/fmchc_python1300c_rst_processing_system7_0_76M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_76M_0/fmchc_python1300c_rst_processing_system7_0_76M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_rst_processing_system7_0_76M_0/fmchc_python1300c_rst_processing_system7_0_76M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_axi4s_vid_out_0_0/fmchc_python1300c_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_axi4s_vid_out_0_0/fmchc_python1300c_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_vid_in_axi4s_0_0/fmchc_python1300c_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_vid_in_axi4s_0_0/fmchc_python1300c_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_vid_in_axi4s_1_0/fmchc_python1300c_v_vid_in_axi4s_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_v_vid_in_axi4s_1_0/fmchc_python1300c_v_vid_in_axi4s_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_square_check_0_0/constraints/square_check_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_2/fmchc_python1300c_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_xbar_3/fmchc_python1300c_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_proc_sys_reset_0_0/fmchc_python1300c_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_proc_sys_reset_0_0/fmchc_python1300c_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_proc_sys_reset_0_0/fmchc_python1300c_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_0/fmchc_python1300c_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_1/fmchc_python1300c_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_2/fmchc_python1300c_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/ip/fmchc_python1300c_auto_pc_3/fmchc_python1300c_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/fmchc_python1300c_ooc.xdc]
set_property is_locked true [get_files C:/Avnet/hdl/Projects/fmchc_python1300c/PZ7030_FMC2/fmchc_python1300c.srcs/sources_1/bd/fmchc_python1300c/fmchc_python1300c.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Avnet/hdl/Projects/fmchc_python1300c/pz7030_fmc2_fmchc_python1300c.xdc
set_property used_in_implementation false [get_files C:/Avnet/hdl/Projects/fmchc_python1300c/pz7030_fmc2_fmchc_python1300c.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fmchc_python1300c_wrapper -part xc7z030sbg485-1


write_checkpoint -force -noxdef fmchc_python1300c_wrapper.dcp

catch { report_utilization -file fmchc_python1300c_wrapper_utilization_synth.rpt -pb fmchc_python1300c_wrapper_utilization_synth.pb }
