// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsquare_check.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSquare_check_CfgInitialize(XSquare_check *InstancePtr, XSquare_check_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi_lite_rgb_1_n_BaseAddress = ConfigPtr->Axi_lite_rgb_1_n_BaseAddress;
    InstancePtr->Axi_lite_rgb_2_BaseAddress = ConfigPtr->Axi_lite_rgb_2_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSquare_check_Start(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL) & 0x80;
    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSquare_check_IsDone(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSquare_check_IsIdle(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSquare_check_IsReady(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSquare_check_EnableAutoRestart(XSquare_check *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL, 0x80);
}

void XSquare_check_DisableAutoRestart(XSquare_check *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_AP_CTRL, 0);
}

void XSquare_check_Set_rgb1_in(XSquare_check *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_RGB1_IN_DATA, Data);
}

u32 XSquare_check_Get_rgb1_in(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_RGB1_IN_DATA);
    return Data;
}

void XSquare_check_Set_n_Mat_out(XSquare_check *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_N_MAT_OUT_DATA, Data);
}

u32 XSquare_check_Get_n_Mat_out(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_N_MAT_OUT_DATA);
    return Data;
}

void XSquare_check_Set_rgb2_in(XSquare_check *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_2_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_2_ADDR_RGB2_IN_DATA, Data);
}

u32 XSquare_check_Get_rgb2_in(XSquare_check *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_2_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_2_ADDR_RGB2_IN_DATA);
    return Data;
}

void XSquare_check_InterruptGlobalEnable(XSquare_check *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_GIE, 1);
}

void XSquare_check_InterruptGlobalDisable(XSquare_check *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_GIE, 0);
}

void XSquare_check_InterruptEnable(XSquare_check *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_IER);
    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_IER, Register | Mask);
}

void XSquare_check_InterruptDisable(XSquare_check *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_IER);
    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_IER, Register & (~Mask));
}

void XSquare_check_InterruptClear(XSquare_check *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSquare_check_WriteReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_ISR, Mask);
}

u32 XSquare_check_InterruptGetEnabled(XSquare_check *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_IER);
}

u32 XSquare_check_InterruptGetStatus(XSquare_check *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSquare_check_ReadReg(InstancePtr->Axi_lite_rgb_1_n_BaseAddress, XSQUARE_CHECK_AXI_LITE_RGB_1_N_ADDR_ISR);
}

